### ISSUE TITLE
Cannot find package `api-plugin-files` locally

### ISSUE THREAD

**Issue by karbal** [reactioncommerce/api-plugin-files#7]
```terminal
api_1    | (node:105) ExperimentalWarning: The ESM module loader is experimental.
api_1    | 17:52:00.795Z ERROR Reaction: Cannot find package 'api-plugin-files' imported from /usr/local/src/app/node_modules/@reactioncommerce/api-core/src/importPluginsJSONFile.js
api_1    |   Error: Cannot find package 'api-plugin-files' imported from /usr/local/src/app/node_modules/@reactioncommerce/api-core/src/importPluginsJSONFile.js
api_1    |       at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:84:13)
api_1    |       at Loader.resolve (internal/modules/esm/loader.js:73:33)
api_1    |       at Loader.getModuleJob (internal/modules/esm/loader.js:147:40)
api_1    |       at Loader.import (internal/modules/esm/loader.js:131:28)
api_1    |       at importModuleDynamically (internal/modules/esm/translators.js:75:23)
api_1    | [nodemon] app crashed - waiting for file changes before starting...
```

Prerequisites
* [ *] Are you running the latest version?
* [ ] Are you able to consistently reproduce the issue?
* [ *] Did you search the issue queue for existing issue? [Search issues]

## Steps to Reproduce
1. Install the plugin locally
2. after creating a blug to forget a file to declare or something. 

## Possible Solution
the core it looks for plugins in docker container first 

### Versions
```json
{
  'reaction-identity': '3.0.0',
  npm: '6.14.4',
  ares: '1.16.0',
  brotli: '1.0.7',
  cldr: '37.0',
  http_parser: '2.9.3',
  icu: '67.1',
  llhttp: '2.0.4',
  modules: '72',
  napi: '6',
  nghttp2: '1.41.0',
  node: '12.18.0',
  openssl: '1.1.1g',
  tz: '2019c',
  unicode: '13.0',
  uv: '1.37.0',
  v8: '7.8.279.23-node.37',
  zlib: '1.2.11'
}
```

**Comment by mpaktiti** [comment]
Hello @karbal. 

If I understand correctly, you have trouble linking this plugin to the core app, while you work on it locally? Can you confirm if that is the case? 

Also, if so, can you confirm that you have followed the steps in this section: [How to link in a local NPM package for a plugin while working on it](https://docs.reactioncommerce.com/docs/devs-update-custom-plugin#how-to-link-in-a-local-npm-package-for-a-plugin-while-working-on-it).

Thank you!

**Comment by karbal** [comment]
Hello @mpaktiti 

The problem comes from core reaction 
because it was the 1st in the list of locally imported plugins, after the integration of another plugin 
I even receive the same error for the new plugin, that the plugin doesn't exist
